title: Winzer eCommerce Documentation
description: Technical documentation for Winzer's multi-brand eCommerce platform
baseurl: ""
url: "https://your-username.github.io/winzer-docs-test"

# Site settings
markdown: kramdown
highlighter: rouge
theme: minima

# Navigation
navigation:
  - title: Platform Overview
    url: /winzer-documentation
  - title: Middleware System
    url: /winzer-middleware-documentation
  - title: Product Data Map
    url: /winzer-product-data-map
  - title: SearchSpring
    url: /winzer-searchspring-documentation
  - title: ShipperHQ
    url: /winzer-shipperhq-documentation

# Collections
collections:
  docs:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
